# Generated by Django 3.2.13 on 2022-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=20)),
                ('locationname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('relateurl', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lgt', models.CharField(max_length=20)),
            ],
        ),
    ]
